# Generated by Django 4.1.5 on 2023-01-03 10:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('details', ckeditor.fields.RichTextField(null=True)),
            ],
        ),
    ]
