# Generated by Django 4.1.5 on 2023-01-03 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='details',
        ),
    ]
